---
# Required for building OVS
- name: Install EPEL and RepoForge repositories
  become: yes
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
      - "http://repository.it4i.cz/mirrors/repoforge/redhat/el7/en/x86_64/rpmforge/RPMS/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm"
  when: ansible_distribution_major_version < '8'

- name: Install packages for OVS building
  become: yes
  yum:
    name: "{{ packages }}"
    state: present
    enablerepo: "epel*, rhelosp-rhel-*"
  vars:
    packages:
      - "dh-autoreconf"
      - "openssl-devel"
      - "python3-devel"
      - "python36-six"
      - "python3-sphinx"
      - "python36-sphinx"
      - "rpm-build"
      - "createrepo"
      - "gcc-c++"
      - "http://mirror.centos.org/centos/7/os/x86_64/Packages/groff-1.22.2-8.el7.x86_64.rpm"
      - "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Font-TTF-1.02-3.el7.noarch.rpm"
      - "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Parse-RecDescent-1.967009-5.el7.noarch.rpm"
      - "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Sub-Exporter-0.986-2.el7.noarch.rpm"
      - "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-Package-Generator-0.103-14.el7.noarch.rpm"
      - "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-IO-String-1.08-19.el7.noarch.rpm"
      - "http://mirror.centos.org/centos/7/os/x86_64/Packages/libevent-devel-2.0.21-4.el7.x86_64.rpm"
      - "http://mirror.centos.org/centos/7/os/x86_64/Packages/unbound-1.6.6-1.el7.x86_64.rpm"
      - "http://mirror.centos.org/centos/7/os/x86_64/Packages/unbound-devel-1.6.6-1.el7.x86_64.rpm"
      - "http://mirror.centos.org/centos/7/os/x86_64/Packages/perl-File-Remove-1.52-6.el7.noarch.rpm"
      - "libcap-ng-devel"
      - "graphviz"
      - "selinux-policy-devel"
  when: ansible_distribution_major_version < '8'

- name: Install RPM packages for OVS building
  become: yes
  dnf:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - "createrepo"
      - "desktop-file-utils"
      - "gcc-c++"
      - "git"
      - "graphviz"
      - "libcap-ng-devel"
      - "libtool"
      - "make"
      - "openssl-devel"
      - "python3-devel"
      - "rpm-build"
      - "selinux-policy-devel"
      - "unbound"
      - "unbound-devel"
  when: ansible_distribution_major_version >= '8'

- name: Set system /usr/bin/python
  become: yes
  command: "/sbin/alternatives --set python /usr/bin/python3"
  when: ansible_distribution_major_version >= '8'

- name: Install PyPi packages for OVS building
  become: yes
  pip:
    name: "{{ packages }}"
    state: present
    extra_args: '--install-option="--prefix=/usr"'
  vars:
    packages:
      - "sphinx"
      - "twisted"
      - "zope.interface"
  when: ansible_distribution_major_version >= '8'

- name: Clone OVS
  git:
    repo: "http://github.com/openvswitch/ovs"
    dest: "{{ ansible_env.HOME }}/ovs"
    depth: 1
    force: 1
    accept_hostkey: true
  retries: 3
  delay: 60

- name: Set high epoch in spec file
  replace:
    dest: "{{ ansible_env.HOME }}/ovs/rhel/openvswitch-fedora.spec.in"
    regexp: '^(License.*\n)'
    replace: '\1Epoch: 2\n'

- name: Adapt spec file
  lineinfile:
    dest: "{{ ansible_env.HOME }}/ovs/rhel/openvswitch-fedora.spec.in"
    state: absent
    regexp: '^BuildRequires:.*(py.*-devel|groff|sphinx-build|-six|-twisted-core|-zope-interface)'
  when: ansible_distribution_major_version >= '8'

- name: Adapt spec file. Add openvswtchX as obsoletes
  lineinfile:
    dest: "{{ ansible_env.HOME }}/ovs/rhel/openvswitch-fedora.spec.in"
    insertafter: '^Obsoletes: openvswitch.*'
    line: "Obsoletes: openvswitch2.11 openvswitch2.10 openvswitch2.12 rhosp-openvswitch"
  when: ansible_distribution_major_version >= '8'


- name: Bootstrap OVS
  args:
    chdir: "{{ ansible_env.HOME }}/ovs"
  command: "./boot.sh"

- name: Initial OVS configure
  args:
    chdir: "{{ ansible_env.HOME }}/ovs"
  command: "./configure"

- name: Build OVS RPM
  make:
    chdir: "{{ ansible_env.HOME }}/ovs"
    target: rpm-fedora
    params:
      RPMBUILD_OPT: "--without check --with build_python3"

# Create a directory to hold the RPMs
- name: Create '/patched_rpms' directory
  become: yes
  file:
    path=/patched_rpms
    state=directory
    mode=0777

- name: Copy new generated RPMs to /patched_rpms
  shell: "cp {{ ansible_env.HOME }}/ovs/rpm/rpmbuild/RPMS/{{ item }}/*.rpm /patched_rpms/"
  with_items:
    - 'noarch'
    - 'x86_64'

- name: Create repository for patched RPMs
  command: "createrepo /patched_rpms"

- name: Setup repository in /etc/yum.repos.d
  become: yes
  template:
    src='ovs_from_source.j2'
    dest='/etc/yum.repos.d/patched_rpms.repo'

- name: Remove EPEL
  become: yes
  yum:
      name: epel-release
      state: absent
