---
# Required for building OVS
- name: Install EPEL and RepoForge
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - "https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm"
      - "http://repository.it4i.cz/mirrors/repoforge/redhat/el7/en/x86_64/rpmforge/RPMS/rpmforge-release-0.5.3-1.el7.rf.x86_64.rpm"

- name: Install packages for OVS building
  become: yes
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - "dh-autoreconf"
      - "http://mirror.centos.org/centos/7/os/x86_64/Packages/groff-1.22.2-8.el7.x86_64.rpm"
      - "libcap-ng-devel"
      - "graphviz"
      - "http://mirror.centos.org/centos/7/os/x86_64/Packages/python-sphinx-1.1.3-11.el7.noarch.rpm"
      - "selinux-policy-devel"
      - "http://mirror.centos.org/centos/7/os/x86_64/Packages/python-zope-interface-4.0.5-4.el7.x86_64.rpm"
      - "http://mirror.centos.org/centos/7/os/x86_64/Packages/python-twisted-core-12.2.0-4.el7.x86_64.rpm"

- name: Clone OVS
  git:
    repo: "git clone https://github.com/openvswitch/ovs"
    dest: "{{ ansible_env.HOME }}/ovs"
    accept_hostkey: true
  retries: 3
  delay: 60

- name: Build OVS
  args:
      chdir: "{{ ansible_env.HOME }}/ovs"
  shell: "./boot.sh && ./configure && make rpm-fedora"

# Create a directory to hold the RPMs
- name: Create '/patched_rpms' directory`
  become: yes
  file:
    path=/patched_rpms
    state=directory
    mode=0777

- name: Copy new generated RPMs to /patched_rpms
  shell: "cp {{ ansible_env.HOME }}/ovs/rpm/rpmbuild/RPMS/x86_64/*.rpm /patched_rpms/"

- name: Create repository for patched RPMs
  shell: "createrepo /patched_rpms;"

- name: Setup repository in /etc/yum.repos.d
  become: yes
  template:
    src='ovs_from_source.j2'
    dest='/etc/yum.repos.d/patched_rpms.repo'

- name: Remove EPEL
  become: yes
  yum:
      name: epel-release
      state: absent
